import type { SlopIndicator } from '../types'
import { boundedScale, ratio } from '../scoring'

const CODE_PATTERNS = [
  /(?:as an ai|ai assistant|generated by)/i,
  /(?:here(?:'s| is) (?:the|an) (?:code|implementation))/i,
  /(?:this section was autogenerated)/i,
  /(?:template(?:d)? scaffold)/i,
  /(?:agent instructions?|prompt instructions?)/i,
  /(?:openspec|spec-driven workflow)/i,
  /(?:please adapt this)/i,
  /(?:TODO: replace with real logic)/i,
]

export function detectCodePatterns(path: string, content: string): {
  patternMatches: number
  signal: number
  indicators: SlopIndicator[]
} {
  const matches = CODE_PATTERNS.reduce((count, pattern) => {
    const found = content.match(new RegExp(pattern.source, 'gi'))
    return count + (found?.length ?? 0)
  }, 0)

  const lineCount = content.split('\n').length
  const density = ratio(matches, Math.max(lineCount, 1))
  const markerSignal = boundedScale(matches, 0, 4)
  const signal = boundedScale((density * 12) + (markerSignal * 0.9), 0.05, 1.4)

  const indicators: SlopIndicator[] = []
  if (matches > 0) {
    indicators.push({
      type: 'AI Boilerplate Trace',
      description: `${path}: ${matches} prompt-like marker${matches === 1 ? '' : 's'}`,
      severity: matches >= 3 ? 'high' : 'medium',
    })
  }

  return {
    patternMatches: matches,
    signal,
    indicators,
  }
}
